#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'traktarr'
        image: 'eafxx/traktarr:latest'

    # CORE (MANDATORY) ############################################################

    - name: 'Including plugins'
      include_tasks: '/opt/coreapps/apps/_plugins.yml'

    

    - name: 'Setting {{pgrole}} Volumes'
      set_fact:
        pg_volumes:
          - '{{path.stdout}}:{{path.stdout}}'
          - '/opt/appdata/{{pgrole}}:/config'


    - name: 'Setting {{pgrole}} ENV'
      set_fact:
        pg_env:
          TZ: 'America/New_York'
          PUID: '1000'
          PGID: '1000'
          DELAY: '2.5'
          SORT: 'rating'
          NOSEARCH: 'no'
          NOTIFICATIONS: 'yes'
          BLACKLIST: 'yes'
          RUNNOW: 'no'
          SKIPUPDATE: 'no'
          APP_BRANCH: 'master'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: 'traktarr'
        image: 'eafxx/traktarr:latest'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: bridge
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'


    - name: 'Update {{pgrole}} for first time use'
      block:
        - pause:
            prompt: "Wait for {{pgrole}} start up"
            seconds: 5

        - name: 'update permission errors for {{pgrole}}'
          shell: 'docker exec {{pgrole}} chmod -cR 775 /opt/appdata/traktarr'

      when: confcheck.stat.exists
